### ISSUE TITLE
Colorized annotations

### ISSUE THREAD

**Issue by justinwoo** [josa42/atom-blame#16]
Any plans to allow for colorizing and customizing colorizing of the gutter? I might start working on this myself and make a PR. (e.g. author, date, commit in colors)

**Comment by josa42** [comment]
I added classes to the gutter. So you can now customize the gutter colors by adding the following lines to your stylesheet (`~/.atom/styles.less`).

``` CSS
atom-text-editor::shadow .blame-gutter {
  .hash   { color: white; }
  .date   { color: white; }
  .author { color: white; }
}
```
